apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configuration
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    path: argo/configuration
    repoURL: '{{ .Values.repoUrl }}'
    targetRevision: {{ .Values.branch }}
  destination:
    namespace: configuration
    server: "https://kubernetes.default.svc"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
