apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configuration
spec:
  project: default
  source:
    path: argo/configuration
    repoURL: '{{ .Values.repoUrl }}'
    targetRevision: "master"
  destination:
    namespace: configuration
    server: "https://kubernetes.default.svc"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true