apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    path: argo/secrets
    repoURL: '{{ .Values.repoUrl }}'
    targetRevision: '{{ .Values.branch }}'
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  syncPolicy:
    syncOptions:
    - SkipDryRunOnMissingResource=true
    - CreateNamespace=true
    automated:
      prune: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
