apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tulip
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    path: argo/tulip
    repoURL: '{{ .Values.repoUrl }}'
    targetRevision: {{ .Values.branch }}
  destination:
    namespace: tulip
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
