{{- $executor := .Values.executor | default dict -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ get $executor "serviceAccountName" | default "ataka-executor" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ataka-executor
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["services", "configmaps", "persistentvolumeclaims"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ataka-executor
subjects:
  - kind: ServiceAccount
    name: {{ get $executor "serviceAccountName" | default "ataka-executor" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ataka-executor
