{{- $ingress := .Values.ingress | default dict -}}
{{- $basicAuth := get $ingress "basicAuth" | default dict -}}
{{- if (get $ingress "enabled" | default false) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ataka
  namespace: ataka
{{- if (get $basicAuth "enabled" | default true) }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: ataka-ataka-basic-auth@kubernetescrd
{{- end }}
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ required "Set ingress.host" (get $ingress "host") | quote }}
      secretName: ataka-tls
  rules:
    - host: {{ required "Set ingress.host" (get $ingress "host") | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000
{{- end }}
