apiVersion: v1
kind: Secret
metadata:
  name: ctfnote-secrets
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/resource-policy": keep
type: Opaque
data:
  db-admin-password: {{ randAlphaNum 20 | b64enc }}
  db-user-password: {{ randAlphaNum 20 | b64enc }}