{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "ctfnote-secrets",
    "namespace": "ctfnote"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "ctfnote-secrets",
        "namespace": "ctfnote"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "db-user-password": "AgCnUxL/MnMU0QjbQlPPv5eSSvSLDwtFqIl/u44jLGv7evWXQLIGwpVbc1Fy0B3MVUejFlYfPTt7RGBH7TRpm7aXd8/PgZozlVu2MMeLmJitTypwCKvP8/lP65vGhaNSezAX+fuXS4a0b2M064vBK884x2XfFwwtq9jQY2jZqy5l1k0wbapsD67PiMHS1Cfut4UKfBa745ZR9wKPimklHQKTvaYjwYGeH7VWFNJOFrfa7fv3JxDr4DKno7e6l6lTooVOe6fYDAUG0LHUiYJdG+cXmNPSoe3uAbgnfFdbyn4LJgL3qBs0icmpMc8UWmEhndW7kA0GBIqpNgd496YzIq7ZN6IlxSEDZS6sB1CZbtMZysKH7vo7YsOcErHJWdBK/i7aqRCTMZaagUG7Ik8PcZVZyukFO8Jqh3Jl1JbKTJrZXcxkBrAz4HuUYXUX9POxE2+xXd0Lp5WhbvSrTA6VOcdHQ22UFjzgnn8TgE+IsXgITNBeY3dm2jFLbZIqT0GLAohkx688C51bN3tz8u42jqBqClt6BdxnqqkxKfeKAsd+0APgLgtJYqfp5KLZkMBcrLrlUYT6fStJgefLdIikRKg4Cwd3XqdY2H4WEc68UeCCRLtpKpLEqv6MNa3DyOfNZQ6vwEJn44u20kU2nQ4v/MvGFHOdvJn8CV3d7XeaOR04BIu6lHkemlUpyEyo9LfI6Ni5+d4FnppjcQhPhdOqcson"
    }
  }
}
