apiVersion: v1
kind: Secret
metadata:
  name: ctfnote-secrets
data:
  {{- if .Release.IsInstall }}
  db-admin-password: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  # `index` function is necessary because the property name contains a dash.
  # Otherwise (...).data.db_password would have worked too.
  db-admin-password:  {{ index (lookup "v1" "Secret" .Release.Namespace "ctfnote-secrets").data "db-admin-password" }}
  {{ end }}