apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: front
  name: front
spec:
  replicas: 0
  selector:
    matchLabels:
      io.kompose.service: front
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: front
    spec:
      containers:
        - image: ghcr.io/tfns/ctfnote/front:latest
          name: front
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
