apiVersion: v1
kind: Secret
metadata:
  name: ctfnote-pad-basic-auth
  namespace: ctfnote
type: Opaque
stringData:
{{- if .Release.IsInstall }}
  auth: {{ htpasswd "user" (randAlphaNum 16) }}
{{ else }}
  auth: {{ index (lookup "v1" "Secret" "ctfnote" "ctfnote-pad-basic-auth").data "auth" }}
{{ end }}
