---
apiVersion: v1
kind: Secret
metadata:
  name: ctfnote-pad-basic-auth-password
  namespace: ctfnote
type: Opaque
stringData:
{{- if .Release.IsInstall }}
  password: {{ $pw := randAlphaNum 16 }}{{ $pw }}
{{ else }}
  password: {{ index (lookup "v1" "Secret" "ctfnote" "ctfnote-pad-basic-auth").data "password" | b64dec }}
{{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ctfnote-pad-basic-auth
  namespace: ctfnote
type: Opaque
stringData:
{{- if .Release.IsInstall }}
  auth: {{ htpasswd "user" $pw }}
{{ else }}
  auth: {{ index (lookup "v1" "Secret" "ctfnote" "ctfnote-pad-basic-auth").data "auth" }}
{{ end }}
