
{{- $existing := lookup "v1" "Secret" "ctfnote" "ctfnote-pad-basic-auth-password" -}}
{{- $pw := "" -}}
{{- if $existing -}}
  {{- $pw = (index $existing.data "password" | b64dec) -}}
{{- else -}}
  {{- $pw = randAlphaNum 16 -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: ctfnote-pad-basic-auth-password
  namespace: ctfnote
type: Opaque
stringData:
  password: {{ $pw }}
apiVersion: v1
kind: Secret
metadata:
  name: ctfnote-pad-basic-auth
  namespace: ctfnote
type: Opaque
stringData:
  auth: {{ htpasswd "user" $pw }}
