{{- $pw := "" -}}
{{- if .Release.IsInstall }}
  {{- $_ := set $ "pw" (randAlphaNum 16) -}}
  {{- $pw = $.pw -}}
{{- else }}
  {{- $_ := set $ "pw" (index (lookup "v1" "Secret" "ctfnote" "ctfnote-pad-basic-auth-password").data "password" | b64dec) -}}
  {{- $pw = $.pw -}}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ctfnote-pad-basic-auth-password
  namespace: ctfnote
type: Opaque
stringData:
  password: {{ $pw }}

---
apiVersion: v1
kind: Secret
metadata:
  name: ctfnote-pad-basic-auth
  namespace: ctfnote
type: Opaque
stringData:
  auth: {{ htpasswd "user" $pw }}
