{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "ctfnote-pad-basic-auth-password",
    "namespace": "ctfnote"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "ctfnote-pad-basic-auth-password",
        "namespace": "ctfnote"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "password": "AgBXeC6PrxXvfGc+fVR7/sCcPk2c9Z04/OEj82ZR+VJeu0oMwB6Fei7rNQzHZP3t3BFL2yYLSjmfIGwYeCk3ENKqW95TccKADqkfCa3Kkf0IYh7hz5zctLhM/5/e1UiCM7GVprC4hgLpbTJY7qMyEWjrKZ9CqI+AGFiXxOFZ0l102A7dD3GPXy0mq5CMIEJ9r7cK+Bz6FhAYMFnwL3RTx+ru6CkR2gov/66ioBhoR+NakFhKV62UZNb73pybsrlG5RhZ+HhB5DtXxE2j/R/Qggy4yNjg353GKV+r2LVKVjduJdKky9uIcRPFvnTyfwFuR/JxlBZN4CqorI2sTISLCO89si9KwEUeHqeX0EUzv1hasnDVToRrDb5fd8E6JnwMOvaatAQyl0Y0pD2vF2Ee93jldoArLiKzvbJSFKW8CtA6TH7dwfxoSYeAuf1EJ9F91yrk2Q7AhLXeSvgmvtzIQ3f6WoKVHW0GmmU5NcDMULdaHPUJDs90NurKnmEwtpuUwwJTQt3FDvdRK7k1s/SojEOjlUDcsBLcuqRnL6BMAJ95qMTpNG0322J+rSK0mPf6JLUtG1tpOgO1ycdZxjmokQG7lhFhJ4n/ifXBVbVNPXqxhVmJV7LB2KlTFO/geGs5SFi2yTJ98drELXPat5Z24b96wk7zy/HT3U8Q00okD+0AC22jcvzPu7go5XlFYSDQbv03xMtIw5tR9dUQ3RBaWBzh2w=="
    }
  }
}
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "ctfnote-pad-basic-auth",
    "namespace": "ctfnote"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "ctfnote-pad-basic-auth",
        "namespace": "ctfnote"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "auth": "AgB+aApki8tX3JYqJTt4Qk57seQzm/8Ae3FhG0JPVgS3asZ9XsTB2O1iSrvh1IylojG0cpZvQdz41nf1AAAReJkUf+EtpiQP0Xs4aitTUDIn0488ks+UMsBDMRNXRE2OReWYIY2pEY9TyCg6JkzKXDhb7D55Ed+oeMHyo00Cx2RDKdkpn5IvyvBAmd5J21QeP9vRaPz4SJQ0VI9AOA0brg+wErpOt2tOX2HtZI/yaxvNqxz0FHcvwgjla56NalkLTzcxSp0xbCiLav+cQ4ufHkST/Z9q3t3OCA/lhgupP6Dti5x5Zgn0JLQ2d2efiYweHWsRzy66T/nP1bPkuu0iyTSq4fzjr6mDgSKEqoOFv2DeiiQYfOutABDBxjXbpWo1K/UKsCoP8YEwiIi8aBupAk9NQH1gSe/LtQSUVfH5cWYTW5uBhqgA++OvTzCHwRIdpEdQ0ulIf5pcz3jhdThGPUVXr5hCamKioYHZ+OzLh1nXBmpWvbmNBiyS6I9rgvUqu3bzDL22iSyUYhFbnYbFm0v1I9/gr4cX+qy0OSEy8EHojswRS/P0ZqIB816PKTwbu/f/x9DxqvEQ5imJGZawcdSY/g5C+P6MSmB+B+ZcyE1NlsjBfqUZvGQa8fM7TrZDn7DnkMRzHAan+H/6AL3EkgBdENCjNabRGowbkrNOL1UkCsx10C7CZeQfBnTi4jo8QMWtMSwv4dAa6jTeHLxX3RDoOZN8MgyLYmRJFocCg9ZD9cqFhNOuLwzQaBU="
    }
  }
}
