
{{- $existing := lookup "v1" "Secret" "ctfnote" "ctfnote-pad-basic-auth-password" -}}
{{- if $existing }}
  {{- $pw := (index $existing.data "password" | b64dec) -}}
{{- else }}
  {{- $pw := randAlphaNum 16 -}}
{{- end }}
{{- /* Use $pw for the rest of the template */ -}}
{{- $pw := (cond $existing (index $existing.data "password" | b64dec) (randAlphaNum 16)) -}}

apiVersion: v1
kind: Secret
metadata:
  name: ctfnote-pad-basic-auth-password
  namespace: ctfnote
type: Opaque
stringData:
  password: {{ $pw }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ctfnote-pad-basic-auth
  namespace: ctfnote
type: Opaque
stringData:
  auth: {{ htpasswd "user" $pw }}
