---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ctfnote-pad-basic-auth-password
  namespace: ctfnote
spec:
  encryptedData:
    password: AgCS9C0AZnk8qXS3ltBqAbvM1XiCuQIGoAaOAPwevDv2GeT2aasW1111o8TYDpSCqKuvXtTR/7jBj7qAUsb+vOzD0z+t6sYBDhR5UdCkid9jARwcJ+mymbXjVW55QJ0aj2JxT9x8E64E6KZSBQqk2qX6dUtsOdM2yegd4qn8l+HfmLsbWyDQsh4fZLOJOagCuXxskQXkwr6nRh3mtU3pHQjQhxURgiSFVJsq7g9YWueEkMYm/AYdS0N7MFvyaNJ2GUoASIUpgS2oe5OORJ7uddoIUekaYCw/w58gnWfyH4qYml0Sa5k0NS3aL9p5GJq+QPDsEzBqRGT/IDXXONMQ8LmM/oV3CHRfyDDf+V7zfi03dUmOd5/YPpydDz7GVNMs9nSPkzdVqrSYc7B3AtRfDCxljN42AdkOArwx44tAagycOlsEqOCDKoZN6MtCk/I3c7RvNLuty7hNFpz9gDwLgyu9fWqQzAVBqC7PZ6JLntnP1HU34o9jj2SQ3aaSD6jqdw78RdfABnhT5iUuCFnzl9KdNrgBcYl/BZyAt9UHDnrlZC0wkRvZOYoAXgaSTGQje8fIWAovzQo6RZkac60VHy3WzLMNIImCQzO/rebkyKgMoEQodk+P7xxo8aNw6CNolQQtkhUDfmB3RjK7o2AhhoOQbvt3FonZHIADcoA6u14EQFB29pm3XBt6juIO48sbsn4bAN+RHarDYASjLisxCYNKNg==
  template:
    metadata:
      name: ctfnote-pad-basic-auth-password
      namespace: ctfnote
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ctfnote-pad-basic-auth
  namespace: ctfnote
spec:
  encryptedData:
    auth: AgBgCVcuUtNi7y+ADYNae7efwTbH99WU3zivAADe/zd9LYvQR7sUPeOnsupjqAcIYlVobBTetNKOxh6mXH9CIEabiQFD8xNVe38r3+khxuXd20wGmDoIwXkcjkR7izvrfv4ptf/k03uJ8r9jR6e2xfzcajjfZleCEpZ/07Ua9SyrM8Rv0SfugYisAlzp8hlwKHkp5mFKP4Lm93NAYVYfbB0gOxgPr9x8bSe44SmX0PmP3K+inOAd2YmIB2OycUnOSZWom4vl4K8guZ8kGHCvu7m1+G86OBzrAhrFCoHXhzd3Hyh8FbxoxbAQAieM37o4kecbzDI+HO2xE/Du48sQ4VQXwbgxkdG+rj8HeqkMpFwpSNVME0L7qVRvGLt8ZZXKUjt87n6cpUFqv5sKMr/K7nbTjmEnhe6/L1Ei8HYP+i6jLBGSixMZ+k2cGmmALe3J3g8jpSyPC3W+SM0Ix4Hpv/lXBnbn/hdHuytupdvDuOIsGDEZH52FZK0wVv6j63tMAvp3jLWSBg5PmZAOb09MO3wEKgkjpEUrMUSkm8pOxbh4scj19vxxZ9NvVUkYg5L+bZzrOomMBJDBhHDGOW7z0mhX2rHTmMjYQmTBRutUsZUK0NAl7BwKUaYc0uE7uGG2xO8vnm6wNpYbyh+QlrUvZSCf/O2BMP62x9Zau9fJZ4dmojR9YdY7p+wZq2oC+HAdzxjrr06AoIWidzzklaXcX3imWmJbs7iBHNvEzpIegE3CbxVTvzMpxqHP6BQ=
  template:
    metadata:
      name: ctfnote-pad-basic-auth
      namespace: ctfnote
    type: Opaque
