---
apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
  namespace: ctfnote
type: kubernetes.io/tls
data:
  {{- $secret := (lookup "v1" "Secret" "ctfnote" "secret-tls") }}
  {{- if not $secret }}
  {{- $ca := genCA "ctfnote.ad.tertsonen.xyz CA" 365 }}
  {{- $cert := genSignedCert "ctfnote.ad.tertsonen.xyz" nil nil 365 $ca }}
  tls.crt: {{ b64enc $cert.Cert | quote }}
  tls.key: {{ b64enc $cert.Key | quote }}
  {{- else }}
  tls.crt: {{ index $secret.data "tls.crt" | quote }}
  tls.key: {{ index $secret.data "tls.key" | quote }}
  {{- end }}