FROM golang:1.19-alpine

LABEL org.opencontainers.image.source="https://github.com/tonitert/ad-infra-k3s"

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build ./cmd/enricher
