---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tulip-http
  namespace: tulip
spec:
  parentRefs:
    - name: traefik
      sectionName: http
      kind: Gateway
    - name: traefik
      sectionName: https
      kind: Gateway

  hostnames:
    - tulip.ad.tertsonen.xyz
  rules:
    # /
    - matches:
        - path: 
            type: PathPrefix
            value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: ctfnote-pad-basic-auth
            namespace: ctfnote
      backendRefs:
        - name: frontend
          port: 3000