apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rsync-keys
  namespace: tulip
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    limits:
      storage: 20M
    requests:
      storage: 10M
