apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: timescale-data
  name: timescale-data
  namespace: tulip
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 10G
    requests:
      storage: 100M
