apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traffic
  namespace: tulip
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    limits:
      storage: 10G
    requests:
      storage: 100M
