---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1u0vfqjaurkmcwfnj9n0ytejkjrytmqv62f5ugjuprgqucu2ctpmqqyrwvy"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1u0vfqjaurkmcwfnj9n0ytejkjrytmqv62f5ugjuprgqucu2ctpmqqyrwvy"
