---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ataka-wireguard-config
  namespace: ataka
spec:
  encryptedData:
    wg0.conf: AgCGsZoBdM0+MoUuS6wX/O1XA53ZvckK2U5qRfhd9OY8ZRT8XAtcVQoT/petQtMaC5EP1UFNJ/xICDJqctt4/5CPp81S5uV34rng5hRArelO9VAPVDHAwjQAjSa/j/JA04mpbOyZsw7ceod85RH5plho/oRFgenKFeaVDdgR3F/P2B7+ev37Jps/hKFc62FwBGgKLyIKVFY6BsYgb4/halnuCfGhv7qFF0H6N1xAeYv/sx0VLYj9vlSbJWB2aFNYtOPguzs4TVyj2Tq8GmepIchiCusM3IXmqlX7hlXH3OSi+roxHrQGbEpAiyXaZoj9Qck8MSt31J2YIE0invsOE4745UiZjjIIXoFvRknBde1NrMY6Qv2QwFxCzAan+2KIC+wNKjcoYr+7G5fNU5Vp4GjshiCRZh0ru8hD53hS5HZQ4ejTcbqc5JzCdpAgJ6uMIK2lXFnXmXTAjrt+JuH4+zWbaovcI9lDESryWVMlzslybjHcrCvZ8aqBnNjdLG5P1AEgGZ8riNwNgACKwMolvUaePsZ/IAdpAQshqwWHBkbsiIO/BxDc6Vy4fUJwvsf41WH9X7JAds2F1btggFtDM3BHbC9G4cUnUtV+GMyH3TiD9usi/WB74uvTZdJN8+3KHvW1fsOqfme3HBdW/hZXAOjO9Kb2SsDe6MRnTpIUd8885oI4G6vhdg9mFTz4oSWaXU/VIkC80w5rGSdhc6wGFjRKQ0Ld+VruvHmsRGOenYk1l5WGTC5O2V/PfQXqd+2X3q4SfNYdqP+pcshZY4YI9oEPepeUEI1DAVhuGeSyN9U9vM5k8S9aXTIP5IZu2ASZuqJ6G4q/9XmhaAqyu2NZ7yJagVEO6ybeGevA5ZTezGhB4wYQwXZPdKnyy1jSMs5NyDg2erzaAXOghcclPiBkA9MM2jgggtbEYOsUfbhgZQix2St3JQQjWzKTeXrIciFaCqHtM32HdGOzgPyAj7hIZRLEh0RSrQqwkMyj6kuukXWOcQRMl4q8kG5j7OKhKT5X8Q==
  template:
    metadata:
      name: ataka-wireguard-config
      namespace: ataka
    type: Opaque
