---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openvpn-config
  namespace: ataka
spec:
  encryptedData:
    vpn.conf: AgBOJqkMg+ewhBWGF6YxiD6SDvZ9YE/dFUGKEtunvMVgw8KAtMhyXkcsbJCw8uBJb8rp4/Ue0wzeewv5nsSkN0F5gb1UW04HnPIk8CzF0s1cD5vvxxTZ4YGY5U2sql59i4b1worKi/37xKxnCgrA0WRA/I1dPb/Ab6wDs9tkf7iyMGF5GqUPnJJCHKEQB1CgiTX8kBI2Ywnr2YAH0yhy0LvbSL7z2xutatkTRALYcdM9m/uFTFAMQJgSsFXvuHtp2fKXBtTOfkeV2Xk1C11MM3Z/veLVFMHysqe8Nwwq0Hm8eXSvuA78aDychINPrZi4xraGXeswRdd2vDVxDS4UimkCLSrjW3NABj+feGgGAc5E90dvNqgfNHuaczCamC2DuXXPdnL9cv7Jmv6ako93LoM1bqJrEXmCYwVfXnTAQ+meo9OAlkT3/CLn3SeENFH4SFuiZ6cDuw5tuxM5sq2W98JNr8T/aeH5FWNKIGf9NAuGl8G2b/ZI6NKEe9KfUlE6HeD8Cj5PGzBf1iBcky7S3nSHxDYWN3V7MfgTj/aOp6aaeqqhps6Vk2e0YSBetIadoLmYWOJxgD2jdXym7ZOP3IwHMAKgR6Bwz8os1sXMy7nSJfd4y6TdVLUlLRQtABLk/z2wVPegWNJ7ICfIH+OhPTOIm3/cR41ZfX7EbQzq84u1Br6Yfq8UMdRZE/3AjFv9cQVZuLUnp3m1XOtiZkgKotQ/pg5LL5/NH/NZ2nT+xPw+aw758jHGSzTSlN7M5atim3GdGaNh6gE=
  template:
    metadata:
      name: openvpn-config
      namespace: ataka
    type: Opaque
