---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ataka-basic-auth
  namespace: ataka
spec:
  encryptedData:
    auth: AgAa+ir0CYFoMontBxVzIyKc+H6Sk8CqEj8lriHtCkkEmmqlnpD61dS/Cfauetpch/J63FrSJz/urcddU1k5PGA2XmViSKAVpmA0BmlCT+sVhOdM+i+oJq/Ad6ubYN+yTdjE5O6yLnw757uSMxRnAfkplk/Uu1RhG/HrM7w613wtQX2JIV55oFRyEr9UJSBnwItYaeZVQo9DewUc+OGtGjyhzLjKzqPRDS5lPdKMC7M6xvKZzUcev2rAn5rSkIcBzMzdqw5b31fK6rAPqanAMD5XV8bQlbK9MhZNkAHrrFRgC7B8bUCH5LRO71yCx3/Lq2u4hcsHog4VCiidngCZRXHA07IbCzuYSw6qwggQcUXFG/Uu0cK3i7hYNJT9/raGqdJkQNz/D/xZKAIp+LoOSE8JnaORy7tTnZq8SlXys9PkbTSE/TUz0unyIPIkarLuu5dVrMseGReCBvZekmdLYscY8McdCNL/Ly/3OTXvR02vlgqV6IoBN4GiOgEJ87YpEjpG56LRSMKK2bVZWgkCJtzyuMyszXcROIUgSSA17h2AHnVOgaN5DfEUe7yAzdS5Xl6zezE8K+Vb6JqaHi8WXKVHVFeavh82d9er3MqRQ3k0m1xkrPZeyhjGlDHtXx0tzuP9oILmYHZa7IN0l2fJdVrxm/bcSzMVJbm2ovyEP95GfpZ7EJutrobfxR0GKq5AdVjl9i1B4UkNt0ckXTfqkdkB/ttCrVM5TQ+XWyAgOD8gXp2hMd6E4rbiy4PvFsA7S6mQQGeckHptfJu2RfXRj/k6hcc=
  template:
    metadata:
      name: ataka-basic-auth
      namespace: ataka
    type: Opaque
