---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ataka-basic-auth
  namespace: ataka
spec:
  encryptedData:
    auth: AgAj0AfkXRdZ4Y2BPUz5cDsR8p+557rz0AGS7FDxeFwSqbiaqiy9HsaVb8z//ZumI5hQtm1riHmcgOrLmwMxvCd9NevIpdaJcsPmDBElJPBPCdtAKCuRMwbOlSqLFBqRQbr4uv/Ojew39XYHr2/nqMprviRSUm6TZQWPK3zq7BxHwao9AtoGdkyQhQQSa455+3IKlAmYPZf2YCuv+2Vek9uGRhkiReiIooH0g7vPYRNiJM64v6pifFHdK89Lqf7iDVN2cLYiLZLK6v1xIQDIjgs876DwmoqVJyCE1If3E+Vf1+447OjfTEYD12J6q5e0M51p+Vbg+aZJ0XXRHa0NH0FETrXo2CQEXc140qkD0/IdMgbFIx03/ElkOX2WGIe22sK6lI1KtJbpdffVfq3ETczhY5mXJEkMuEnbs0zK4U5dyOxVpynnmLoRM35jRpdGZaZBODiucZhZYVHtaLb6h74U/9L37aZqu2EnVO9uMhgSLhIl6SYawZRRuEjXm1gEiPUI8d5PWevZc4e0f1ufhqunY4n5JDRA/ge+MP6Moi12dGOm0Gw71lse9S3mjCJmiUJNEIJo66mPmN0qDLE6UIsli9/RZ8x2C9Tocu+IbhddZCaRcK9vvJPu46lplGr6WRPgnyC/ocFXxen44bmR7dFNleobH/pPF5kvd2VSsuxTElsPpx0ePH+BkHsnuI95SS3J6blBr0cieFBQndVukIUC1/SeRycnjWBJtEoMqF3//1qUm9/uGpAvn7xKB+2iTBJFTA1E2jrsxKS5Do8lO9mXBng=
  template:
    metadata:
      name: ataka-basic-auth
      namespace: ataka
    type: Opaque
