---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ataka-wireguard-config
  namespace: ataka
spec:
  encryptedData:
    wg0.conf: AgAQDfSsagsdfyhNK+C5daritJqOyfnw8cAj48Jkmn7mcp7VE+tr+eHqRJZLJzqtPkddi5hdhShcdcjK7QKesDbrEWTHWgLT9mUvPTl29VqVTOFZoeSTS3CyrWYcqsJWZget5OsxulH8STyeaqLySA5nwa+H0uDuiTAeGakomXzJ/maxhVj1fMeRvYKxbCjAdKo4FU+F/8SW/aDUd1OANeyoyDEkxlkqIKwOjtZ5j1agOQ50cCG4TGfl5HmLqHqfz0eu1K4QnrEXeEFwT9LnOQNLgQ+65Oeb1IwwTi/Z6xLNjas6ZE8pUSBgCMqsZUSNLbP6oeOTsXa5T3wti/XA2a62Oab3a3nEdr9fQr0pv9ACzomjfIl131pnP6/EmxQrTItff7gm4+wK88aaPI6Yv8syMajdWPT/Wbvg7HTH5b3sqWF6yRA//kmb88es4Y9lquP9X5EsLZJnchevJqxGs7XB2y/y7+f24P/PzTUV5nlyQWU5LABZ+89mYZeuEGSb9CmPhtxQfIraTehX59VxaNT4qexx5VDglrPdSZx5HBueaY9kKObGzG5JqU/7j5P+57BdvXLHJLhdk/g90Z2sVmGkSI15YfIzB90CH8aWEO7llolbvInwJza+dP/+Gx4BGX0RN9HvxaUB8/0BQANruaiiZgHkIFXngH6lQwEEfoH2J/+BoTopV6xxWAhw8sIAQq5YTHHYaN4k6zLVuBzFDiAj9N3JlOBG3ETyAY8nSP/IvbSe0JKLXJcCNTsPfZX1lcwjrru1j+BS0Ps7HmPWo8fEURnq0uj7YXjCqfaqYFYFbTjxa00zMAEX6FQYJjSXR3jW0WkV30G+QUGLPwNm3aZChH8PlK3VQU+E5OWIQwzF5sQPkbeuZaVw3z06ol70plVcVPFrX9kn+oYjSj6HtGAnWk10WWzIBG+OCM8T0ac60jxjsItulqES4NyBKok1p2LOTb3vOA==
  template:
    metadata:
      name: ataka-wireguard-config
      namespace: ataka
    type: Opaque
