---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ataka-wireguard-config
  namespace: ataka
spec:
  encryptedData:
    wg0.conf: AgBqAp/Rj33Z3ialb8JH0Jacbwc15Ho2d+9rPCTgMFlIInGQghJsDRFddgwLFWTvKrILwheIFDmqnVxlJEX6BQsYBe94m5sqnn2Wjsh/+F6tpje10nl1w/sszE/k4SjaVH90+z7TF8EavqtKk8QaM3vGKyKdV4O60Ek9twDrXHUEC4V6IC2I/M2qfYE+gddzs1GMA6D4tBPBuUWo4fXhSa8NmwHe9ifSXxrNOJvQPCjnavCG5QfQIDcKxQKWHW081hs+j0J74toLL4DDfBHBDHKuO++LEwRDHC+QIa24rzcZBjlPoBiPGkfd63tZjiYSu3ussbRVdEAWfdaCpKV+ykx4gArHVbpf+x3sYvBvrLLLloMMZweFRwvtcUXr9TpfcMbZAdCmpAGL/QYMF6yfP8XeH4LabCGPIxmE23Ergi5dx3AfrzbHS6zx9XqZK8lnk+J6kU76SPWmQQqQMPmn+F9beD+opZAV26jbkPFN3V4+AP5rqUgweKWZbMWa8fzXhi/QdAvrSydPIlrNQHg8aDMQE7WYfB8vlWBdEJuCVQXy5QOlBqSLjMAJpGmd7fiYYQ4wHDGtLjHxYWqDdjg4RJms5nHFzG69qzNa7cWQN6mS9cvOnDFC8wH69Vj2luZMbxel9venMeYMwaYaJTItbIcHUQYyHiqelcO/4pIRwN8e8qfnWAuL4SJ6ZIPjiuGyD7VLINK3u8QL+g3axLXC0JwLNV8jSHmSJpju+9buixQt6S4WcHOn37YTFhC7Y96QPm9oV0jyX15HnZy+XuDIUrEyq2B8/trKHIlGVFH50TvnpEeSCtTwV/bDCU/U1SIQBNvTvifIDYWOti9NL0go+NuT412ii2zV7q6aDYOM+M6p7YlfkHr811D04yt8e7574ssLTLAmr3Cciq9xs9pSAO2rPUksPNuiuaLBYzNFj0Socil+mSLBQl6No5hGyDRaoY6hWoekpQ==
  template:
    metadata:
      name: ataka-wireguard-config
      namespace: ataka
    type: Opaque
