---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ataka-basic-auth
  namespace: ataka
spec:
  encryptedData:
    auth: AgCKEj2jS4qrMF25E5vxgmQju+OnoJfaukllxUGAYky3ou8/wR1WabzXqlULaLvnXsY7oI3a/2s+RYAcRbHstO09alN9KH0sasf0UIXhaGXPqEWoAau0tJ7qVYUQipWXKFclJ61Mxz2Oh7+aNR37OeE8CG9mlcCLb6Iayx/sb19JfWIXrtulo+Sq0TA4jIjR2fGphbl0McCnDt8UlpTzWNbYyTScy6YKvUAPWnOhCIX3P7fC7SwZTiUJvO+RO5IZBV19EVQvMF80YRMQz4FP80+28wxt/CB+EWtx7lxZDPQUUEF2r8i5pNc6x8h6gZNH1M8MpuD/dxAx9gGfkm+n3/vwStQT+IQ7j6DE20jMcvvtrh1dYO2oFG+NpmgnIm8BU/lYGZohlXFMbAJbj/AIFufaF6zdRg5/rVMQGLJA4Glm7aWh7I8Wd43juDjykbNRA51s+SNk+7+ZSCplxHshnH4y2s/KuvqVxnphMm1LY58tic3v/Cxlc8qKKFRMfXPY6dOXGXA5PSs8uIzKukbsp4gF435lNemsPJbv8FVgiah6UCE2M7jPr5bcPP0Dj1CnlBesgXWbGFvbNLzNM3KrMPuNDtaoX3GV0TZPLsEauKBdjpwfJzZCu1MQElqxNQj/n4IDEjm7JgVFn6Nnfz4/xZzqovA32DlC4itRRyYhtnWHI7wdP6gnb5ECso/Rx4XuE8bVpH+Vh+e5gh/PJAVn2EbJk6lNmWOmx8Jr3uDIaUGZyNORj0f0R3mDU2o6B78lRCwYp6RWM7g+HstcGgqFxK3/41E=
  template:
    metadata:
      name: ataka-basic-auth
      namespace: ataka
    type: Opaque
