---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-config
  namespace: flag-submitter
spec:
  encryptedData:
    wg0.conf: AgAaacWgGIyuvsPslIQmmgoXt6B2HO6MGU5h5lTUjiG/lyppVIQW7+OogO9aK6I7uD10MeFDR68y3j9pAfBONE5345Ew63ysbu33oGfIA6yrzlN6gj9toM60ReUogOB4Mu/hkNyzXyNdvy0KSmrQlCRR2wEJRBURprAGZnTwQcvZ7juAx26b6UrQ/fRREFr3ByWtRnzuFMInXFJJYftmuOC1At/JKF8Ebg1NHjgsjvMAW43r3Oc2xeLxoie9+koA/mNki3Ik38gG7dABSglgai3g5gu2XBS0ab9bT30qL+whoK7QXUkOkrnF+zB85A0v3/uXd6hvpv4XNAHDt5C9W+mkjPMyDjRhr5kOz9nCpOSYv7NA+1uYSd3wZA5gRXnLn8bwZVSKuOijUKeEhLYNUO+dSvCKEKh9pwje0/uPAwv2NnLH0XBgOGQYcobNV3fVxZHnQE3IVsG4iZpR3jw4sYgX/QT2/i/4SiYwFPrSHVGMZzvA8lriUfMg2qIsrLLj8FJLjMdafd1zlB/+Sr9mDj/bOhz8NiPW2JOnSH9an7ju1nptzBetzECnhFyA6qHlcPSrIzw70JZMY5ChJj5yAUIXRij/oR+5Bvn13emTxrsEZO1/Awe764h3JHNrEIBqwvSGrgfCQ0Rnszp+mpPuKckH1yRnH2RDw8nbPUwseoDSrI28UH02pNwh+1YRPLiMi1aC3Uj4MAnZui5vPSL8/Bmc3Vy4V5rH6crDbLR+zxFFkTRHMzLd2P5CHtHkue2lnSvaw1Mqf1qF+i1IYyFpKZaPkV31lZtptAFYDYhYjW9R/0d3BKEytvqQ+mhp6WMveIdD7TwSfbZIGFOCJT4gvoRMer77H+dvPxV8DPE+sm4joQlkz7LyDjXfPUXX2Y69VBkJLjQGUap8mNBzTc5sF6zyL50LwCqtC/qekYP19uFSLGiH9IF71Cy2XX1NBW3KuNQQW05GwAbXvsCu+BIzwmEKoOQGkbc/fHbSLUBdD4xmQgsHgB4lvC+ip/looLlc76qXB8y22VeK9X/1
  template:
    metadata:
      name: wireguard-config
      namespace: flag-submitter
    type: Opaque
