---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ctfnote-secrets
  namespace: ctfnote
spec:
  encryptedData:
    db-user-password: AgByDMn4gQomkByQODaYqojfu0aW8JdmIUBn+kKI4IouBlYoTWFC0fzQ00QuVAtSt+W5Uqk01vLm2FY5xQdkocNWokQ9BJTFMNKDbjgAY2l0+vNUdHvoTdNxaniawmW/N/AQloVTwD9kWk/6Q4GWJM5j8ILA1zMPNahMR9aVHQuH4fR5SwqiPiCdsYFikmjRrcVCT4wQcDmcaplU2pOXYhP989RPlLWDbgHKfIWj6Wl29VoR1NCISO6jf3LZwOcIvPcRabDNVjbq3vAbx2WjmPocigU6nQMFIRYSWCfosk6pCaiA1dg4Qakp5o7InNQ6BtWokYtTr0O+P9tUSumMq9Io5wrLUseTSoX0UTFRpsSYNfBiOf/W3TmBjTE9VxVmi1wsVwl9ncT5o+cVeuHMe++Oom3CPJaGysDwAce+Ois2JgLDb83q39Dl4XzTUXGrdV1gDbYgmsuATi0eJzEaggWFRcXx81T69iJpRj43b/95gi0Dq9jyhl2fvdTtEW+ZI/cjv20WYh2qxr2qccNGv2x9l7dNDYZIGP2wnPRAVgdDbNGCBd+iW6qMR9qZidCpuof0obiYU9TvZ9/dUBvudQfzLs3ECoXXrXEo99a2ffUGTSjSkxdIAOjcO0WP+9WHu7dDdeimFjmgpS+B1D6S0QUrKdt9f0Wtu2Q2YlNvj/ljbtwTARZwBxV8KwVmkSnnMDRjDaFkydXClFkPR0YGri7QlDWGAXRnJ9nj+DbmN5vQEg==
  template:
    metadata:
      name: ctfnote-secrets
      namespace: ctfnote
    type: Opaque
