---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ctfnote-secrets
  namespace: ctfnote
spec:
  encryptedData:
    db-user-password: AgCeSFZc5C656VVguNzgF13OOf7oYN+5DmOz3F9lL1vvi7iOk84U9t5MalKKC0F/u7gFplCMiIFDDUpv5QgXuE7sjObxEkSWm0uGrkYb7jj1qWi9/SNVO1HunYFap/drc98YjZdflUK2VPVDF8YVIyAkLlLpvALbefYb6dRn/GdKUs0JfInc9w82EI1PB8obFyFw5mNLF7Jj2QyS4D5ftoettyXf/ICR1dzo+aCrzgE5uvQkN8ctHNypG35MQh22g8ZO8CVZt7gQ1VOZ514gvNj+CzkZbr0mJCnIOCcUlsH3RkSPlDbEAIoa2DRVYi3M+IzXqnVnZEvpgka4sWiunmnOxWMs1H3wOzKFN4oXjqzrgpBnTPIfNGIdI0W7l0u5kQp5Sa/2qKu3dpAUaLhqpFoiziL8A210lnxjLK+T75LIEHNN9Y3/BFjxwZWcJ34gX/O/n4mS/a76VDdqT+ahejf+3jI8Q4tSsdKAvoUJzKsKqXicsswSq5zcSzlbdI9atVvPKp4aeuKIKn6bCinOT6Ihf/r6WDUoykyWFPxpWpGbfBCOd/9RWRZpO0oFWnfH5aRkl7DqLzahCI9E76InvF2LJB0g0WcSQ5bQxsZLZPCzmLBZPu/Ttq0AMJ3kYJQ+9+Hu4dFWqe2IIGmGJYxFUXpqR+5qRCPjwGbP7CD7fx+/88++/LHxAJux0jf70jB4MuyMgUS8avCUvJEued5Ah+r0waEgLfuD480XFHa+nM1o3A==
  template:
    metadata:
      name: ctfnote-secrets
      namespace: ctfnote
    type: Opaque
