---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ctfnote-pad-basic-auth
  namespace: ctfnote
spec:
  encryptedData:
    auth: AgC4S5VcrK9kd/7d0V1JCXmdpGUKmuZ05LTtazKIGo9Br9zP3eW6Ig8Opkvd3YzZvUQwD0U/hkK9twf7+yXjdYeTKZttQG/0/csnmJJdFKx3ty5zNUaxWsS4fZDl8ljanx3d9I22yGnShQJEt56LtuS3mT9txoBtA0SiTIBYGLRnLA3qz95BkLpKsx0/7zgrkrTobeEPOqbG7NC1vAt/TeUGHVNOFfV/vcaIgC/AvaxiIIhDo9c38YWRa/8P2WkzUP24YYJoxgmxqXFDh9/jZtqYjjMcJqlVTD+hn7CEYbYI/HMo6wu/GMuL7ZZpAYZry1M68mBKilyvJzsdqLkLTKQIc42U/RnC8Id1JyRgBjwBwFS7I66iD+jlgjlFj88nkcdN/aMElJFNLqT7jn/CjulmccZT4enWDBRD+q6bTWpxRlBSpp05YNPKenUXO3WcihYu5WnP0nHPaH7zCWJ2jrnmNhMteIxsNg2RJoiHiVnjTEagGtYbyrXOjStvoYFAKuEo+0OclUiNd16/8fFQ6ig5ubDi44ip7MXoX9Zid3GdAvelrKyv4J4ffjaku+/mlyGwLKPR1thxIxwqZXxj102RdItc3NRmjV7ChN5PKm+0OpU3kBrrWyeJj/pq55nTL6qNX/+hCPI32BOhY88Gn8uhuvcNSlur9RLItZAR0aBcZz3AL+8n9WwPRObcNEkLbK52mV+ZjtjeUNXB4t6mDyW3FNrEviSgUPmq/8xj/TT2s/KqFAsp+09CfYd9S2ro8gewDYYoi7P60/pBtYP1v7viSFA=
  template:
    metadata:
      name: ctfnote-pad-basic-auth
      namespace: ctfnote
    type: Opaque
