---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ctfnote-pad-basic-auth
  namespace: ctfnote
spec:
  encryptedData:
    auth: AgCiCd9h7brHBvvY2azJE97aIod2pzLc+KuTNM85ARkPzyQLe6zdQ6MgIQvMG8ORmHJob9MiqPB8E4edEIKPi22zvfXAXc9FTLthitk8qp2k7XJKYB+DsR4IME8jz6EJzJPaG9Hnp0HCW9OcAhSMYgehiMgdg+uylh2vlPFQqnkp01Diygyc7LPY5LACnPZym04DSjZQoqVPULgaOTyeflcpLNYWfn5dTrPGBv85BEGB0iyB4CXK01m3ORSSFxCmRuKR9OIsO/tKlR5I6gSLE6xE3/cnlRPdcUsGEiKrNjxrx12RvGERPsyl3jEGD245iSDoC22TNpEC58HhKt4jwXOWNkPJPRxbI+L7HmG91bHiJ2Z6ZOqOf82cimQmzBf8ZpPrBLralF5WmSkntBF8/shRU4V+MgKg92LuyvRy3ZB8GDj5itc0NRTMUU0Zr/rgbnzCg3oCCPSuUJopMxzdGpycJb2E9iupnERMAqWo7hik/vO204P53HRUzHPd5OOPGiE+J3VU4V3u8PDEJcNBOzK1jeUO6DeFNmQTITx3mlc0Jz7yurr2dngGNhzAppuU9yqDQvPFg5DM327O9DKeZeshEBpibE6jPbmFdRqxYv0efU92HY1EZrRqoZNhErI244lihWXgtgK+sSYFaWyJk2KR7YfiwiVlqlw2Bck0+2HoTAxWXmWMag46jl63FbYtNJYm6MFuSAZfbftINAkFscDJjdTiUPMWMUcl+JiB++Xf43IJfkl3bO2srORq45//8rKmlh3b7+T9nf7jhc5WsnPhiiKs
  template:
    metadata:
      name: ctfnote-pad-basic-auth
      namespace: ctfnote
    type: Opaque
