---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ctfnote-secrets
  namespace: ctfnote
spec:
  encryptedData:
    db-user-password: AgCUf0Cnngo9RGnSOod5BfWbOny8Q4xz/aHdvhQzQ6mObgMLnMLWyFwjzdd+7VQ5R9pCXC/mpbohGjrdFbk+KtwrZLG8HVmAJmbaSj+t1Lo+DG7R4JNjQVUPXUf41UbOYTrQAGdo7ilQAGLvH0sQxq83RIfLXCqDDU9ZS2HzsKFOMv2XGmOXBqdIJOSVFU2qHiaJsb5Aed/oNvkRMb3iK+DYi8V/vvdu98eGzmJXz01CJtgwT0E2LTG2+x9IpFSTgFWNcCxyNdfix/uHcstpE9SlCiZD5XgpqTTG8LF9rOKlMArjFprxc6d5drDfCQ4gQqkx8LLp+5LlKp5LLRSN2PyKizoDf92mrmLPNiQ9rbJwR6VzhjsVI/Ywj1L4YYgc27LDuhfUghwuOsWHY1D04jdTdS7QKGQRyTozRjPlQfuJ2JjSRM+pD75RbdfTaqoUSd7kIyxLEYaMXlJbzo4H6chk8F97VOLH6hzVFkRo9VP8aHXbhDyTaPWSA9nSN7ZvOYZMsc30CVjlC4zyRDDI11hsNgeWlcBePIQq90vcFeVZiw9cdsJPHBCJVK8RhmHbLEDv/VD7cagBO/8kJl2MaviRnujcsyW5hgkKkfhkeeG/h58Kc6eCdKYG5DlhKUldDcqzpPb3NTgQFPLudUtR80GUgGcH1TXN4SU7i/bAskSikCwMX3Ra71+PHwYWYoJjsRP9qBnvmEfFMRsWhzKTINjcHJbWXoSM3R8htWWCy2VB9A==
  template:
    metadata:
      name: ctfnote-secrets
      namespace: ctfnote
    type: Opaque
