---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ctfnote-pad-basic-auth
  namespace: ctfnote
spec:
  encryptedData:
    auth: AgCe4lwKkYHYyXKkNGvZswhz7vjmtRzucTmebq53P60C2HRaXCAg8vDD2Ht5vBKpvu8PicbGyE1r5bgSNHav6fx9pvVCt7uCIlObBgUxEdi7n55rR53+vEBwF6fTDUs2JzvdcWaTdtlYVYuJynphDZ/IU88yMToaTAF9Elbyct/HwySmQgQJJrH5cmwNMwPNoob9XrUo1+/tObNKpGqxTIu+yx+wqqYJwyar9g02C3iZAeM1BTzXUDBAuHvX+J/wts+eUEyS3k/PFVTsbRXlhCaJf2HOl6cphl34efkG+5rbsyUEH3+zBt061wd5xtch8t8ipJFUkancPDLcxR8DKl5A2RVDtO5ZB6rODG9k5WLgsQZKUOMIBmUtBz7Rg21ZsRTVmRn6EtmfKpN0X5xPQ/t5fUPAaOSYmy4NAEromgulLgAbpANeQ7/ycPK7KNA82qDeseXm1+OO6PHMrGfOQ6FQyB1KGA0nKpBZm760TCyxUe70OtudN0nCpPa8A5rEhvKpkf+cdARWTsUutNkJOyKuLB/4SoCDvFwFAMgu+W3L9qVf36S2YPX2d1vTukm7FPJlSnOgHHj1v4GB3SSnxhcmZ4qahkeNVrYKxlI5vSkibjjN+bbcXU2PPWfHahXgrsIzWtaCn/LP2IGAqi028sXcMUAEL2l1zk+ltw+zFB8m/X1CwJ3xtHLZTpNmmUn1DtakiFQ9u1izpq23oV/qved4nPWODR0WRgMW62GA9bn1tMDwQQgea18R88If57K7ZY7q3ChwYnwBYp7STk/vhtFH2SY=
  template:
    metadata:
      name: ctfnote-pad-basic-auth
      namespace: ctfnote
    type: Opaque
