---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tulip-basic-auth
  namespace: tulip
spec:
  encryptedData:
    auth: AgAdPUFVSFQVSDz00ksylBbIUxZzA6qKRdBPeu0htJCAJYqUS6D1Mwp39nv/mb9wqlh1q+iTuDTScRgx2QKltCwxShoH+yeoY7nWxfszR3YIOIDOz3dEFCTHN/vDl74S2zTVPVDVrScGYD1CvPwYaSswXVKc/o6N07CMzRT6xmBxqDAPLQwUh1utMSIUIeSAviF2wKXxg2PqwVbDzBnha//V+bSq7vtNmVW1UhQ12ViIVYxffpmGtZVBR/Gcw97SgQfkgpkFCU9zEl68+Rl7G4BElHV0hWZObdVUtdbwq8NlVMd2b1jllpmLsVUI4Ys6NYwe+y8weSPP6eZg1tYjQbgd+yN2mOrGXEh/RVFSIvYZyGT4nH4M/ewkN7rDU+sn4nWE0y6PQunls01pwF/KyZYIrQnrQlBZtGkLk8pWnExrMPR4L2c3/dpkv4luMFdj04OsK9lyTTsxgvwCC5IpVBhyygnyLVqHObqk5MPo5avYkzPJ5eNSe7xEV1jjhkTI9lV7BpF3XMSjDcVvu1KRngjU+HUWWrLHI8WlSpDgMdsrf0y76MG02aLBkoVdODpMykE8RKlSo6ga5Dt/6NsTyinBtyHr9kPmppoFu8mevVe/NcB0DQXGdLJcfZZ+rqr4z/WqUKVJQgdtx3ZtRdqKCwINT7fYmT0DfDtNK4P7Gsz8w75zs2z+VNw1YxHnNOzAq3bTnvO8+bb+os98ExwWBDN6WYHkGfJdEy6RwNfizaBKi109f1/0zok8ND6FIXZCONyHafHNqjCObewqqxDn+tuiPUw=
  template:
    metadata:
      name: tulip-basic-auth
      namespace: tulip
    type: Opaque
