---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tulip-basic-auth
  namespace: tulip
spec:
  encryptedData:
    auth: AgBRqPp6lBC4wz/mYu7F6iCpnDKcPf3Bpl4ltqh8UHNxmYGjc3JdM+EwgaOEwb22TKr5sxxBHJsO2K6J/DbBeOVLBlkGznXGFzU//nz5OR8GJX/LbXRV6r0EiFsfNsMklhVeLYrkKPplFR0dma/dvlun5EkZt4PE3vpLsv5jwzlf4VjQLPMners70b438yix1YWzODP2LcPdQw+0U3t9fWSX8FHOfcfe0TUV+wv42MuDYfhMUR8dDImYHv5RIZtO0iq1VX9PJ47CAW88nTGb02KNJ9vD36ufP+kkK9ce5Q+AQL+Tqtpl3g3AdBejRr7YNp0vIzm4v9DaMoYMLdAScu5kmqOde9JmkE0tu5UWp6tLd/PB399/KTBJ9bDOpYLYKQOeYrSNbGhJgNSpnksCuVwXSnBwIAsTCAmlouLxlh82ZTSDCPHs5DUGfZOJRZ/oRDBnHcBUNgCc0VMHt4EQ22cCJTBIgK47Ralm3Wd7KnsQEFa/3ytFlBk/b2Zf1WXeuYr/ICrU/rZ9WstfWpwAiXfxU66GifsKSbXkG2LCpo6vTW3y5hiwqP7pLKbx8+81Kg3uz8rOLe1N5Rl/wvoVuDmlq2Zmrq7vof3/AYgFtpia25GmwcYE6cOFQNZleB7OIWDqaa7jyXpw4TQLWoYNUkZN87APv5DU2xL7bYQ2Apx07AKc7mXuVEsKzg/xV7OJW1CV3DKQdLX1WDpQ5X/YI3emAJhojleMeI7yCYw5vs2qDo4+lyvd5vH+qWm3AjPTYZr5EOGUY3Wb7aHumQBOWpRraB8=
  template:
    metadata:
      name: tulip-basic-auth
      namespace: tulip
    type: Opaque
