---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tulip-basic-auth
  namespace: tulip
spec:
  encryptedData:
    auth: AgBnzzqOSQ0hUMmh+Tqp3qxCwX0UUCqlTGslAR5lwVmaH9kDu8RSq/IahhRjYxB24UiuNg3C/gRi83bva1HBPgxeS0uL4TRAT7xQh5cgDkkzVP85jftl3rdVHIUK7J0l5Oqt2JJXem+7hzkRTFPYMHPRthzSmhW3myqGSbT1SxOYMrl4TsbIo5gUBeJEoVO3ydKVo15713d6hoYx4ne8C4WhjgglQUdBZ3wHHSVT9Fhc29+PIXWf9v6UXwqhNr5/k+Q7iB28EEWU5SZGg/Y639YCrh502RM4VhHGD45b/sEcsPa0YQ4xukVR4uzwqEjIa7TUsHYqLluxLT7C7Y2kD7x8Qpu5VaApyUkgbbK81qTtbpi7GB14QOUPV3pc9QS5dqGVCuBuqkCn89L1X2SHy4lUI4/knglDWRJvsGQ2lVYrCZ9eltP7VcE71aaqRSB9QscBYAfO2dNJf12GOlSgjhi80wkCDxwL4UzDowUXeK6fx+58ENigyZErr0k++0fK7XMoy0CcZvQueLnO1fbnSqKiFHzXl4VLUujv52eqzOCkOfYP11g/pEv+DgOkREVSObZg8BfeiOoezcQTf/053C2SCzMv/hoKTmt21yrbnU8vxP2fiJzwF4XmzW/EzanlG2lb7ctETyrayeY2U0LPs/92IC9hqLZ6Ee3J196Fr1yVq2WN46eF8YQHJOfqdBbGrT0K7EU8a3fBx2bVZkaQTAUxzWtwE5nKbec7H1liI21Q2Xqw1hN5mzMaVOt5pKPlt+N5rKgGglmWTvTKjJ/ZtAHg2Qs=
  template:
    metadata:
      name: tulip-basic-auth
      namespace: tulip
    type: Opaque
