---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-config
  namespace: tulip
spec:
  encryptedData:
    wg0.conf: AgBFSkWj3jBzjgTGnCWWiawBOQ2Np3qaiIdWCzcl3T/m2z/EpodiQxjLKioGxDHzOZ/hbEjF4lZfpUiRRVDtg4d1vWLsj7QiFkYEa7UWQYDWGSgHXdUWmOMoML9YpGfYq8WkWrHfMfRckqnZ8HqD/LiC5grjXxa9DDbhYwHN3gXxj8vtkCVgg2BF/xxu+1azzqba6Jk8Kh8UEDOSW0Gnlc7ePIIr2Yh+1eIrAS7lKAWdDoVRZK7CSnq3XR5gRdZonO/30uJdZH9ICMJ3H/YtTpHMT1IYROAso0PXSAy47yD59VsDBL2eJysnztyLAG1KnecJCCK/eI0g1ErZEMBNIkWokN4jG0zrlox+nPUMby/YXKGuzzoPb8o3KB03uEJgoG8VNUYz+VTar2odPRtxk7my0JACP5kcuuA1Q6g7lKu0RSXnbSHaowyrHBsNRu7r8rczUy4BukzmWPFBacPMz6JoBfn/H2HJPq/7KliKMeIKV8K881qqu6iZpOC0KL3m93Xnmcj5e996mgSdy6roSRf3XVoA7w3au6O+9kGRoWDGkjvlUgli3+STwo6dkkbOuxm0gzYQYQR9gJp3ehdU5nqErD0NDYIlNCo3Dv26I+wKCbEXyc/oTYo5ssM6RlVW54H7hZFL1VdvqVPXoJlpB4g3QvlVHOV6B1ksA1M/IYgzaX7rZXxlh5kZ2FWRgp4Bmk6D+y+E9STL1ssldZds1Rlshg3bGQ/n18N2DPRFXK+mUx8vlhA3M5W0vNIPw/IdnPRcO6Zn2TbTXmjHVADLky0YDHW1RVI64wdNfzNFpXaYTFdI0I4Nx5dWctDSBHSIbdjQzVaD1slQOqJrSV/mxKw0ZwtROGdfJHO31GnEcBcPffCSc6JtMYFlUcuX7sgwo6ssTPHcjF/DceT1+SNvojULVXq/+QZnhsf+7i8pgGoI5Pl0JZlCkDTkusoSEMOelBbUKX6SY85FvzM+ey/EQIfeJZXIzGZirui92xONiJqf1lS8/J6xqtcRV+wrnMW70KMtjySJgq0h95MY
  template:
    metadata:
      name: wireguard-config
      namespace: tulip
    type: Opaque
