version: "3.7"
services:
  db:
    build:
      context: "./db"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ctfnote
      POSTGRES_USER: ctfnote
      POSTGRES_MULTIPLE_DATABASES: hedgedoc
    volumes:
      - ctfnote-db:/var/lib/postgresql/data
    networks:
      - ctfnote
    ports:
      - "5432:5432"
  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:1.10.3
    environment:
      CMD_DB_URL: "postgres://ctfnote:ctfnote@db:5432/hedgedoc"
      CMD_URL_PATH: "pad"
      CMD_IMAGE_UPLOAD_TYPE: "filesystem"
      CMD_CSP_ENABLE: "false"
      CMD_RATE_LIMIT_NEW_NOTES: "0"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - pad-uploads:/home/hackmd/app/public/uploads
    networks:
      - ctfnote
    ports:
      - "3001:3000"
volumes:
  ctfnote-db:
  pad-uploads:
networks:
  ctfnote:
