FROM python:3.10

LABEL org.opencontainers.image.source="https://github.com/tonitert/ad-infra-k3s"

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

STOPSIGNAL SIGINT

CMD ["python3", "webservice.py"]
