BASIC_AUTH_USERNAME = ""
BASIC_AUTH_PASSWORD = ""
DEFAULT_ATAKA_BASE_URL = ""


def get_basic_auth():
    if BASIC_AUTH_USERNAME and BASIC_AUTH_PASSWORD:
        return BASIC_AUTH_USERNAME, BASIC_AUTH_PASSWORD
    return None
