apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  repo: https://quay.io/jetstack/charts/cert-manager
  chart: cert-manager
  targetNamespace: cert-manager
  version: "1.18.1"
  valuesContent: |-
    config:
        apiVersion: controller.config.cert-manager.io/v1alpha1
        kind: ControllerConfiguration
        enableGatewayAPI: true
    crds:
      enabled: true