ingress:
  enabled: true
  host: ataka.ad.tertsonen.xyz
  basicAuth:
    enabled: true

openvpn:
  enabled: false

wireguard:
  enabled: false
  image: ghcr.io/tonitert/ad-infra-k3s/ataka-wireguard:latest
  secretName: ataka-wireguard-config
  configKey: wg0.conf
