{{- $ataka := .Values.ataka | default dict -}}
{{- $wireguard := get $ataka "wireguard" | default dict -}}
{{- if (get $wireguard "enabled" | default true) }}
apiVersion: v1
kind: Secret
metadata:
  name: ataka-wireguard-config
  namespace: ataka
type: Opaque
data:
  {{ (get $wireguard "configKey" | default "wg0.conf") | quote }}: {{ (required "Set ataka.wireguardConfig in secrets/chart/values.yaml" (get $ataka "wireguardConfig") | toString) | b64enc | quote }}
{{- end }}
