{{- $ataka := .Values.ataka | default dict -}}
{{- $basicAuthUsername := (required "Set ataka.basicAuthUsername in secrets/chart/values.yaml" (get $ataka "basicAuthUsername") | toString) -}}
{{- $basicAuthPassword := (required "Set ataka.basicAuthPassword in secrets/chart/values.yaml" (get $ataka "basicAuthPassword") | toString) -}}
apiVersion: v1
kind: Secret
metadata:
  name: ataka-basic-auth
  namespace: ataka
data:
  auth: {{ htpasswd $basicAuthUsername $basicAuthPassword | b64enc | quote }}
type: Opaque
