apiVersion: v1
kind: Secret
metadata:
  name: ctfnote-pad-basic-auth
  namespace: ctfnote
data:
  auth: {{ htpasswd .Values.basicAuthUsername .Values.basicAuthPassword | b64enc | quote }}
type: Opaque