apiVersion: v1
kind: Secret
metadata:
  name: ctfnote-pad-basic-auth
  namespace: ctfnote
data:
  auth: {{ htpasswd .Values.basic-auth-username .Values.basic-auth-password | b64enc | quote }}
type: Opaque