---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "devcontainer"

env:
  DOCKER_IMAGE_NAME: runner-image
  DOCKER_REGISTRY: ghcr.io

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths: ["Dockerfile"]
  pull_request:
    branches: ["master"]
    paths: ["Dockerfile"]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}

jobs:
  build-container:
    name: Build and Push runner container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: k3s
          file: ./k3s/Dockerfile
          platforms: amd64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:latest,ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}